### PR TITLE
Add viewport versions

### LINKED ISSUE #136: Option for SuperClusterer algorithm bounding box
Hello @jpoehnelt,

Is there a reason why 2 months ago (#60, src/algorithms/supercluster.ts:96), you switched the bounding box for getClusterer() in the SuperClusterer algorithm from a dynamic `[west, south, east, north]` to a static `[-180, -90, 180, 90]`?

We were working on a project, and we had some huge performance issues (tested on `Ubuntu 20.04 LTS` and `macOS 12.1 Monterey`).

Running on 2.3k markers, going above 100 clusters on the entire map would literally crash the browser.

Digging through the SuperClusterer algorithm, we found the bounding box set on those previously mentioned static numbers. Changing back those values for the dynamic ones, fixed it.

Correct me if I'm wrong, but it seems relevant to only want the algorithm to operate on currently visible clusters (instead of the entire world).

Thank you,
Have a lovely day.

(Related pull request : [!135](https://github.com/googlemaps/js-markerclusterer/pull/135))

### PR DESCRIPTION
**Pull request by mwaddell**
I am seeing the same issue as @leighhalliday with respect to performance degradation with very large datasets when using the SuperCluster algorithm and also with the Grid algorithm when beyond maxZoom.

This PR implements the following to address these issues:

- Adds `NoopViewportAlgorithm` which does no clustering but does filter markers by an extended viewport
- Updates `AbstractViewportAlgorithm` and `GridAlgorithm` to use `NoopViewportAlgorithm` when beyond maxZoom instead of `NoopAlgorithm`
- Updates `SuperClusterAlgorithm` to implement `AbstractViewportAlgorithm` and to respect the viewport when generating clusters (though not on the intial clustering, so caching is not impacted).
- Updates `AbstractViewportAlgorithm` to calculate `changed` accurately
- Adds unit test coverage to existing `NoopAlgorithm` and for new code changes

Fixes #136, #417, #419

### CODE REVIEW

**Comment by findhumane** [comment]
This works wonderfully, thank you!

**Comment by findhumane** [comment]
Fixed with a `forceRecalculate` boolean which is set to `true` on map pan (`idle` event) [only `supercluster` algorithm tested):

<details>
<summary>diff</summary>

```diff
diff --git a/src/algorithms/core.ts b/src/algorithms/core.ts
index ab351b1..5a69f92 100644
--- a/src/algorithms/core.ts
+++ b/src/algorithms/core.ts
@@ -36,6 +36,11 @@ export interface AlgorithmInput {
    * @see [MapCanvasProjection](https://developers.google.com/maps/documentation/javascript/reference/overlay-view#MapCanvasProjection)
    */
   mapCanvasProjection: google.maps.MapCanvasProjection;
+
+  /**
+   * The `forceRecalculate` option requires cluster recalculation.
+   */
+  forceRecalculate: boolean;
 }
 
 export interface AlgorithmOutput {
@@ -124,6 +129,7 @@ export abstract class AbstractViewportAlgorithm extends AbstractAlgorithm {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   }: AlgorithmInput): AlgorithmOutput {
     const state = { zoom: map.getZoom() };
     let changed = false;
@@ -144,6 +150,7 @@ export abstract class AbstractViewportAlgorithm extends AbstractAlgorithm {
           ),
           map,
           mapCanvasProjection,
+          forceRecalculate,
         }),
         changed: changed,
       };
@@ -159,6 +166,7 @@ export abstract class AbstractViewportAlgorithm extends AbstractAlgorithm {
         ),
         map,
         mapCanvasProjection,
+        forceRecalculate,
       }),
     };
   }
diff --git a/src/algorithms/grid.test.ts b/src/algorithms/grid.test.ts
index edd3c72..b7e88e1 100644
--- a/src/algorithms/grid.test.ts
+++ b/src/algorithms/grid.test.ts
@@ -32,6 +32,7 @@ test("calculate should return changed: true for first call when zoom > max zoom"
   const grid = new GridAlgorithm({ maxZoom: 16 });
   grid["noop"] = jest.fn();
   grid["cluster"] = jest.fn();
+  const forceRecalculate: boolean = false;
 
   map.getZoom = jest.fn().mockReturnValue(15);
 
@@ -39,6 +40,7 @@ test("calculate should return changed: true for first call when zoom > max zoom"
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   map.getZoom = jest.fn().mockReturnValue(17);
@@ -47,6 +49,7 @@ test("calculate should return changed: true for first call when zoom > max zoom"
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(changed).toBe(true);
@@ -55,6 +58,7 @@ test("calculate should return changed: true for first call when zoom > max zoom"
 test("calculate should return changed: false for next calls above max zoom", () => {
   const mapCanvasProjection = new MapCanvasProjection();
   const markers: google.maps.Marker[] = [new google.maps.Marker()];
+  const forceRecalculate: boolean = false;
 
   const grid = new GridAlgorithm({ maxZoom: 16 });
   grid["noop"] = jest.fn();
@@ -65,6 +69,7 @@ test("calculate should return changed: false for next calls above max zoom", ()
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(result.changed).toBe(true);
@@ -73,6 +78,7 @@ test("calculate should return changed: false for next calls above max zoom", ()
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(result.changed).toBe(false);
@@ -81,6 +87,7 @@ test("calculate should return changed: false for next calls above max zoom", ()
 test("calculate should return changed: false for next calls above max zoom, even if zoom changed", () => {
   const mapCanvasProjection = new MapCanvasProjection();
   const markers: google.maps.Marker[] = [new google.maps.Marker()];
+  const forceRecalculate: boolean = false;
 
   const grid = new GridAlgorithm({ maxZoom: 16 });
   grid["noop"] = jest.fn();
@@ -91,6 +98,7 @@ test("calculate should return changed: false for next calls above max zoom, even
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(result.changed).toBe(true);
@@ -101,6 +109,7 @@ test("calculate should return changed: false for next calls above max zoom, even
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(result.changed).toBe(false);
diff --git a/src/algorithms/noop.test.ts b/src/algorithms/noop.test.ts
index b890d99..38d1f9a 100644
--- a/src/algorithms/noop.test.ts
+++ b/src/algorithms/noop.test.ts
@@ -28,6 +28,7 @@ beforeEach(() => {
 test("noop should not filter and return changed: false", () => {
   const mapCanvasProjection = new MapCanvasProjection();
   const markers: google.maps.Marker[] = [new google.maps.Marker()];
+  const forceRecalculate: boolean = false;
 
   const noop = new NoopAlgorithm({ maxZoom: 16 });
   noop["noop"] = jest.fn();
@@ -39,6 +40,7 @@ test("noop should not filter and return changed: false", () => {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(getBounds).toHaveBeenCalledTimes(0);
@@ -48,6 +50,7 @@ test("noop should not filter and return changed: false", () => {
 test("noop should not filter and return changed: false", () => {
   const mapCanvasProjection = new MapCanvasProjection();
   const markers: google.maps.Marker[] = [new google.maps.Marker()];
+  const forceRecalculate: boolean = false;
 
   const noop = new NoopViewportAlgorithm({ maxZoom: 16 });
   noop["noop"] = jest.fn();
@@ -59,6 +62,7 @@ test("noop should not filter and return changed: false", () => {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(getBounds).toHaveBeenCalledTimes(1);
diff --git a/src/algorithms/noop.ts b/src/algorithms/noop.ts
index c008e6f..718c57c 100644
--- a/src/algorithms/noop.ts
+++ b/src/algorithms/noop.ts
@@ -37,9 +37,10 @@ export class NoopAlgorithm extends AbstractAlgorithm {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   }: AlgorithmInput): AlgorithmOutput {
     return {
-      clusters: this.cluster({ markers, map, mapCanvasProjection }),
+      clusters: this.cluster({ markers, map, mapCanvasProjection, forceRecalculate }),
       changed: false,
     };
   }
@@ -60,6 +61,7 @@ export class NoopViewportAlgorithm extends AbstractViewportAlgorithm {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   }: AlgorithmInput): AlgorithmOutput {
     return {
       clusters: this.cluster({
@@ -71,6 +73,7 @@ export class NoopViewportAlgorithm extends AbstractViewportAlgorithm {
         ),
         map,
         mapCanvasProjection,
+        forceRecalculate,
       }),
       changed: false,
     };
diff --git a/src/algorithms/supercluster.test.ts b/src/algorithms/supercluster.test.ts
index 90bbf25..19f6787 100644
--- a/src/algorithms/supercluster.test.ts
+++ b/src/algorithms/supercluster.test.ts
@@ -28,13 +28,14 @@ beforeEach(() => {
 test("should only call load if markers change", () => {
   const mapCanvasProjection = new MapCanvasProjection();
   const markers: google.maps.Marker[] = [new google.maps.Marker()];
+  const forceRecalculate: boolean = false;
 
   const superCluster = new SuperClusterAlgorithm({});
   superCluster["superCluster"].load = jest.fn();
   superCluster.cluster = jest.fn();
 
-  superCluster.calculate({ markers, map, mapCanvasProjection });
-  superCluster.calculate({ markers, map, mapCanvasProjection });
+  superCluster.calculate({ markers, map, mapCanvasProjection, forceRecalculate });
+  superCluster.calculate({ markers, map, mapCanvasProjection, forceRecalculate });
   expect(superCluster["superCluster"].load).toHaveBeenCalledTimes(1);
   expect(superCluster["superCluster"].load).toHaveBeenCalledWith([
     {
@@ -51,6 +52,7 @@ test("should cluster markers", () => {
     new google.maps.Marker(),
     new google.maps.Marker(),
   ];
+  const forceRecalculate: boolean = false;
 
   const superCluster = new SuperClusterAlgorithm({});
   map.getZoom = jest.fn().mockReturnValue(0);
@@ -72,6 +74,7 @@ test("should cluster markers", () => {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(clusters).toHaveLength(1);
@@ -102,6 +105,7 @@ test("should not cluster if zoom didn't change", () => {
     new google.maps.Marker(),
     new google.maps.Marker(),
   ];
+  const forceRecalculate: boolean = false;
 
   const superCluster = new SuperClusterAlgorithm({});
   superCluster["markers"] = markers;
@@ -115,6 +119,7 @@ test("should not cluster if zoom didn't change", () => {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(changed).toBeFalsy();
@@ -127,6 +132,7 @@ test("should not cluster if zoom beyond maxZoom", () => {
     new google.maps.Marker(),
     new google.maps.Marker(),
   ];
+  const forceRecalculate: boolean = false;
 
   const superCluster = new SuperClusterAlgorithm({});
   superCluster["markers"] = markers;
@@ -140,6 +146,7 @@ test("should not cluster if zoom beyond maxZoom", () => {
     markers,
     map,
     mapCanvasProjection,
+    forceRecalculate,
   });
 
   expect(changed).toBeFalsy();
@@ -148,6 +155,7 @@ test("should not cluster if zoom beyond maxZoom", () => {
 
 test("should round fractional zoom", () => {
   const mapCanvasProjection = new MapCanvasProjection();
+  const forceRecalculate: boolean = false;
   mapCanvasProjection.fromLatLngToDivPixel = jest
     .fn()
     .mockImplementation((b: google.maps.LatLng) => ({
@@ -171,7 +179,7 @@ test("should round fractional zoom", () => {
   superCluster["superCluster"].getClusters = jest.fn().mockReturnValue([]);
 
   map.getZoom = jest.fn().mockReturnValue(1.534);
-  superCluster.cluster({ map, mapCanvasProjection, markers });
+  superCluster.cluster({ map, mapCanvasProjection, markers, forceRecalculate });
   expect(mapCanvasProjection.fromDivPixelToLatLng).toHaveBeenCalledTimes(2);
   expect(mapCanvasProjection.fromDivPixelToLatLng).toHaveBeenNthCalledWith(1, {
     x: -240,
@@ -187,7 +195,7 @@ test("should round fractional zoom", () => {
   );
 
   map.getZoom = jest.fn().mockReturnValue(3.234);
-  superCluster.cluster({ map, mapCanvasProjection, markers });
+  superCluster.cluster({ map, mapCanvasProjection, markers, forceRecalculate });
   expect(superCluster["superCluster"].getClusters).toHaveBeenCalledWith(
     [0, 0, 0, 0],
     3
diff --git a/src/algorithms/supercluster.ts b/src/algorithms/supercluster.ts
index c2ab27e..6ef715b 100644
--- a/src/algorithms/supercluster.ts
+++ b/src/algorithms/supercluster.ts
@@ -60,7 +60,7 @@ export class SuperClusterAlgorithm extends AbstractViewportAlgorithm {
     this.state = { zoom: null };
   }
   public calculate(input: AlgorithmInput): AlgorithmOutput {
-    let changed = false;
+    let changed = input.forceRecalculate == true;
 
     if (!equal(input.markers, this.markers)) {
       changed = true;
diff --git a/src/markerclusterer.ts b/src/markerclusterer.ts
index 632f826..09dba57 100644
--- a/src/markerclusterer.ts
+++ b/src/markerclusterer.ts
@@ -159,10 +159,14 @@ export class MarkerClusterer extends OverlayViewSafe {
     }
   }
 
+  public renderIdle(): void {
+    this.render(true);
+  }
+
   /**
    * Recalculates and draws all the marker clusters.
    */
-  public render(): void {
+  public render(forceRecalculate: boolean = false): void {
     const map = this.getMap();
     if (map instanceof google.maps.Map && this.getProjection()) {
       google.maps.event.trigger(
@@ -174,6 +178,7 @@ export class MarkerClusterer extends OverlayViewSafe {
         markers: this.markers,
         map,
         mapCanvasProjection: this.getProjection(),
+        forceRecalculate: forceRecalculate,
       });
 
       // allow algorithms to return flag on whether the clusters/markers have changed
@@ -197,7 +202,7 @@ export class MarkerClusterer extends OverlayViewSafe {
   public onAdd(): void {
     this.idleListener = this.getMap().addListener(
       "idle",
-      this.render.bind(this)
+      this.renderIdle.bind(this)
     );
     this.render();
   }
```

</details>

**Comment by mwaddell** [comment]
Applied @findhumane forceRecalculate boolean into this branch.  I agree that this fixes the issue they reported.

**Comment by vicb** [comment]
@amuramoto any update on this PR? i.e. could it be merged, does it need updates?

**Comment by MeisterOfPizza** [comment]
Agreed, these improvements would make a huge difference. @amuramoto @wangela Any updates on this PR?

**Comment by mwaddell** [comment]
I recreated this PR as #640 (forked from my personal repo instead of my corporate one) so that I can enable maintainer edits.  Feel free to merge either.

**Comment by MeisterOfPizza** [comment]
@mwaddell Are you able to upload to npm? Would appreciate it! 😀

**Comment by mwaddell** [comment]
> @mwaddell Are you able to upload to npm? Would appreciate it! grinning

@MeisterOfPizza I just pushed it to https://www.npmjs.com/package/@pangaeatech/markerclusterer for testing - I'm not planning to maintain/update that branch though.

**Comment by MeisterOfPizza** [comment]
@mwaddell Works great, thank you! 😁

**Pull request closed without merging**
